/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./pages/**/*.{ts,tsx}', './app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        /* ── shadcn/ui backward-compat (HSL) ───────────────────── */
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'var(--color-blue-500)',
          foreground: 'var(--primary-foreground)',
          50: 'var(--color-blue-50)',
          100: 'var(--color-blue-100)',
          200: 'var(--color-blue-200)',
          300: 'var(--color-blue-300)',
          400: 'var(--color-blue-400)',
          500: 'var(--color-blue-500)',
          600: 'var(--color-blue-600)',
          700: 'var(--color-blue-700)',
          800: 'var(--color-blue-800)',
          900: 'var(--color-blue-900)',
        },
        gray: {
          DEFAULT: 'hsl(var(--gray))',
          50: 'var(--color-gray-50)',
          100: 'var(--color-gray-100)',
          200: 'var(--color-gray-200)',
          300: 'var(--color-gray-300)',
          400: 'var(--color-gray-400)',
          500: 'var(--color-gray-500)',
          600: 'var(--color-gray-600)',
          700: 'var(--color-gray-700)',
          800: 'var(--color-gray-800)',
          900: 'var(--color-gray-800)',
        },
        blue: {
          10: 'var(--blue-10)',
          50: 'var(--color-blue-50)',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        point: {
          DEFAULT: 'var(--color-red-500)',
        },

        /* ── Semantic color tokens ─────────────────────────────── */
        surface: {
          primary: 'var(--surface-primary)',
          secondary: 'var(--surface-secondary)',
          background: 'var(--surface-background)',
          elevated: 'var(--surface-elevated)',
          disabled: 'var(--surface-disabled)',
          danger: 'var(--surface-danger)',
        },
        'text-token': {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          disabled: 'var(--text-disabled)',
          inverse: 'var(--text-inverse)',
          accent: 'var(--text-accent)',
          danger: 'var(--text-danger)',
        },
        interactive: {
          primary: 'var(--interactive-primary)',
          'primary-hover': 'var(--interactive-primary-hover)',
          'primary-active': 'var(--interactive-primary-active)',
          secondary: 'var(--interactive-secondary)',
          destructive: 'var(--interactive-destructive)',
          disabled: 'var(--interactive-disabled)',
        },
        overlay: 'var(--overlay-bg)',
        status: {
          'success-bg': 'var(--status-success-bg)',
          'success-text': 'var(--status-success-text)',
          'warning-bg': 'var(--status-warning-bg)',
          'warning-text': 'var(--status-warning-text)',
          'error-bg': 'var(--status-error-bg)',
          'error-text': 'var(--status-error-text)',
          'info-bg': 'var(--status-info-bg)',
          'info-text': 'var(--status-info-text)',
        },
      },
      spacing: {
        1: 'var(--spacing-1)',
        2: 'var(--spacing-2)',
        3: 'var(--spacing-3)',
        4: 'var(--spacing-4)',
        5: 'var(--spacing-5)',
        6: 'var(--spacing-6)',
        7: 'var(--spacing-7)',
        8: 'var(--spacing-8)',
        9: 'var(--spacing-9)',
        10: 'var(--spacing-10)',
        11: 'var(--spacing-11)',
        12: 'var(--spacing-12)',
      },
      borderRadius: {
        lg: 'var(--radius-l)',
        md: 'var(--radius-m)',
        sm: 'var(--radius-s)',
      },
      fontSize: {
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        md: 'var(--font-size-md)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
      },
      fontWeight: {
        normal: 'var(--font-weight-regular)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        nav: 'var(--shadow-nav)',
        card: 'var(--shadow-card)',
        calendar: 'var(--shadow-calendar)',
      },
      keyframes: {
        rolling: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-100%)' },
        },
        rolling_clone: {
          from: { transform: 'translateX(100%)' },
          to: { transform: 'translateX(0)' },
        },
        'calendar-accordion-down': {
          from: { height: '150px' },
          to: { height: 'var(--radix-calendar-accordion-content-height)' },
        },
        'calendar-accordion-up': {
          from: { height: 'var(--radix-calendar-accordion-content-height)' },
          to: { height: '150px' },
        },
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        rolling: 'rolling 10s linear infinite',
        rolling_clone: 'rolling_clone 10s linear infinite',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'calendar-accordion-down': 'calendar-accordion-down 0.2s ease-out',
        'calendar-accordion-up': 'calendar-accordion-up 0.2s ease-out',
      },
      fontFamily: {
        pretendard: ['Pretendard'],
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
