export const HEADING_1 =
  'text-[var(--font-size-5xl)]/[var(--line-height-tight)] font-bold' as string;
export const HEADING_2 =
  'text-[var(--font-size-4xl)]/[var(--line-height-tight)] font-bold' as string;
export const HEADING_3 =
  'text-[var(--font-size-3xl)]/[var(--line-height-tight)] font-bold' as string;
export const HEADING_4 =
  'text-[var(--font-size-2xl)]/[var(--line-height-tight)] font-bold' as string;
export const HEADING_4_BOLD =
  'text-[var(--font-size-2xl)]/[var(--line-height-tight)] font-bold' as string;
export const HEADING_4_SEMIBOLD =
  'text-[var(--font-size-2xl)]/[var(--line-height-tight)] font-semibold' as string;
export const HEADING_5 =
  'text-[var(--font-size-md)]/[var(--line-height-relaxed)] font-semibold' as string;
export const TITLE_1 =
  'text-[var(--font-size-xl)]/[var(--line-height-normal)] font-bold' as string;
export const TITLE_1_BOLD =
  'text-[var(--font-size-xl)]/[var(--line-height-normal)] font-bold' as string;
export const TITLE_1_SEMIBOLD =
  'text-[var(--font-size-xl)]/[var(--line-height-normal)] font-semibold' as string;
export const TITLE_2 =
  'text-[var(--font-size-lg)]/[var(--line-height-normal)] font-semibold' as string;
export const TITLE_3 =
  'text-[var(--font-size-base)]/[var(--line-height-relaxed)] font-semibold' as string;
export const BODY_1 =
  'text-[var(--font-size-xl)]/[var(--line-height-relaxed)] font-normal' as string;
export const BODY_2 =
  'text-[var(--font-size-base)]/[var(--line-height-relaxed)] font-normal' as string;
export const BODY_3 =
  'text-[var(--font-size-md)]/[var(--line-height-relaxed)] font-normal' as string;
export const BODY_4 =
  'text-[var(--font-size-sm)]/[var(--line-height-relaxed)] font-normal' as string;
export const BODY_4_REGULAR =
  'text-[var(--font-size-sm)]/[var(--line-height-relaxed)] font-normal' as string;
export const BODY_4_MEDIUM =
  'text-[var(--font-size-sm)]/[var(--line-height-relaxed)] font-medium' as string;
export const NAV_TEXT =
  'text-text-token-primary text-center text-[var(--font-size-xs)] font-medium';
